<a href="https://colab.research.google.com/github/Shambhuraje1919/Machine_Learning_Paractice/blob/main/credit_card_fraud.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("uditjain13/credit-card-fraud-detection-2026")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'credit-card-fraud-detection-2026' dataset.
Path to dataset files: /kaggle/input/credit-card-fraud-detection-2026

In [8]:
import os
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as pl

In [4]:
os.listdir(path)

['credit_card_fraud_2026.csv']

In [5]:
df = pd.read_csv(os.path.join(path,'credit_card_fraud_2026.csv'))

In [6]:
df.head(3)

,transaction_id,amount_usd,merchant_category,card_type,auth_method,channel,device_type,is_foreign_transaction,hours_since_last_txn,txn_count_last_24h,...,ip_country_mismatch,billing_shipping_mismatch,cvv_retry_count,velocity_score,time_of_day_hour,day_of_week,is_ai_generated_scam_attempt,merchant_risk_score,prior_disputes,is_fraud
0,1,42.86,Restaurants,Visa,OTP,Online,Android Phone,False,13.54,2,...,False,False,0,0.1,18,3,False,42.3,0,0
1,2,4.75,Online Retail,Mastercard,3D Secure,Online,Android Phone,False,0.71,2,...,False,False,0,25.8,12,4,False,28.3,0,0
2,3,77.18,Groceries,Mastercard,3D Secure,Online,Mac,False,0.35,5,...,False,True,0,42.3,5,0,False,24.7,1,0

In [7]:
df.columns.unique()

Index(['transaction_id', 'amount_usd', 'merchant_category', 'card_type',
       'auth_method', 'channel', 'device_type', 'is_foreign_transaction',
       'hours_since_last_txn', 'txn_count_last_24h', 'distance_from_home_km',
       'card_age_months', 'customer_age', 'account_balance_usd',
       'is_new_merchant', 'used_vpn', 'ip_country_mismatch',
       'billing_shipping_mismatch', 'cvv_retry_count', 'velocity_score',
       'time_of_day_hour', 'day_of_week', 'is_ai_generated_scam_attempt',
       'merchant_risk_score', 'prior_disputes', 'is_fraud'],
      dtype='object')

In [17]:
fig = pl.scatter_3d(df, x='time_of_day_hour',y = 'hours_since_last_txn',z =  'cvv_retry_count',color='is_fraud')
fig.show()

In [21]:
pl.line_3d(df, x='ip_country_mismatch',y = 'hours_since_last_txn',z =  'cvv_retry_count',color='is_fraud')

In [24]:
df.dtypes

transaction_id                    int64
amount_usd                      float64
merchant_category                object
card_type                        object
auth_method                      object
channel                          object
device_type                      object
is_foreign_transaction             bool
hours_since_last_txn            float64
txn_count_last_24h                int64
distance_from_home_km           float64
card_age_months                   int64
customer_age                      int64
account_balance_usd             float64
is_new_merchant                    bool
used_vpn                           bool
ip_country_mismatch                bool
billing_shipping_mismatch          bool
cvv_retry_count                   int64
velocity_score                  float64
time_of_day_hour                  int64
day_of_week                       int64
is_ai_generated_scam_attempt       bool
merchant_risk_score             float64
prior_disputes                    int64
is_fraud                          int64
dtype: object

In [28]:
df= pd.get_dummies(df, columns= ['is_ai_generated_scam_attempt','billing_shipping_mismatch','ip_country_mismatch','used_vpn','is_new_merchant','is_foreign_transaction'],drop_first=True)

In [40]:
df = pd.get_dummies(df, columns=['card_type','auth_method','channel','device_type',],drop_first=True)

In [49]:
df = pd.get_dummies(df,columns=['merchant_category'],drop_first=True)

In [50]:
df.dtypes

transaction_id                         int64
amount_usd                           float64
hours_since_last_txn                 float64
txn_count_last_24h                     int64
distance_from_home_km                float64
card_age_months                        int64
customer_age                           int64
account_balance_usd                  float64
cvv_retry_count                        int64
velocity_score                       float64
time_of_day_hour                       int64
day_of_week                            int64
merchant_risk_score                  float64
prior_disputes                         int64
is_fraud                               int64
is_ai_generated_scam_attempt_True       bool
billing_shipping_mismatch_True          bool
ip_country_mismatch_True                bool
used_vpn_True                           bool
is_new_merchant_True                    bool
is_foreign_transaction_True             bool
card_type_Discover                      bool
card_type_Mastercard                    bool
card_type_RuPay                         bool
card_type_Visa                          bool
auth_method_Biometric                   bool
auth_method_No Authentication           bool
auth_method_OTP                         bool
auth_method_PIN                         bool
channel_Contactless                     bool
channel_In-App                          bool
channel_Online                          bool
channel_POS                             bool
device_type_Android Phone               bool
device_type_Mac                         bool
device_type_POS Terminal                bool
device_type_Smart Watch                 bool
device_type_Tablet                      bool
device_type_Windows PC                  bool
device_type_iPhone                      bool
merchant_category_Electronics           bool
merchant_category_Fuel                  bool
merchant_category_Gaming                bool
merchant_category_Gift Cards            bool
merchant_category_Groceries             bool
merchant_category_Healthcare            bool
merchant_category_Online Retail         bool
merchant_category_Restaurants           bool
merchant_category_Streaming             bool
merchant_category_Travel                bool
merchant_category_Utilities             bool
dtype: object

In [51]:
df.head()

,transaction_id,amount_usd,hours_since_last_txn,txn_count_last_24h,distance_from_home_km,card_age_months,customer_age,account_balance_usd,cvv_retry_count,velocity_score,...,merchant_category_Fuel,merchant_category_Gaming,merchant_category_Gift Cards,merchant_category_Groceries,merchant_category_Healthcare,merchant_category_Online Retail,merchant_category_Restaurants,merchant_category_Streaming,merchant_category_Travel,merchant_category_Utilities
0,1,42.86,13.54,2,22.35,39,25,1080.71,0,0.1,...,False,False,False,False,False,False,True,False,False,False
1,2,4.75,0.71,2,35.28,47,33,4463.72,0,25.8,...,False,False,False,False,False,True,False,False,False,False
2,3,77.18,0.35,5,9.82,51,59,366.25,0,42.3,...,False,False,False,True,False,False,False,False,False,False
3,4,1.69,3.42,6,19.72,48,28,1345.29,0,28.9,...,False,False,False,False,False,False,False,True,False,False
4,5,261.68,2.43,2,17.68,43,36,4192.59,0,3.9,...,False,False,False,False,False,False,False,False,True,False

In [64]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score , confusion_matrix
from sklearn.ensemble import RandomForestClassifier

In [53]:
x = df.drop('is_fraud',axis=1)

In [54]:
y = df['is_fraud']

In [55]:
x_train , x_test , y_train , y_test = train_test_split(x,y,random_state=42, test_size=0.2)

In [65]:
model = LogisticRegression()
model2 = RandomForestClassifier()

In [68]:
model.fit(x_train,y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning:

lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression

LogisticRegression()

In [67]:
model2.fit(x_train,y_train)

RandomForestClassifier()

In [58]:
df.shape

(20000, 51)

In [69]:
pred = model.predict(x_test)
pred1 = model2.predict(x_test)

In [71]:
pred1

array([0, 0, 0, ..., 0, 0, 0])

In [70]:
pred

array([0, 0, 0, ..., 0, 0, 0])

In [73]:
print('accuracy_score Logistic', accuracy_score(y_test,pred))

accuracy_score Logistic 0.9835

In [72]:
print('accuracy_score RandomForest', accuracy_score(y_test,pred1))

accuracy_score RandomForest 0.9835

In [80]:
from xgboost import XGBClassifier

model3 = XGBClassifier(random_state=42)
model3.fit(x, y)

importance = pd.DataFrame({
    "Feature": x.columns,
    "Importance": model3.feature_importances_
})

importance = importance.sort_values(by="Importance", ascending=False)
print(importance.head(20))

                              Feature  Importance
16           ip_country_mismatch_True    0.074807
24              auth_method_Biometric    0.063059
8                     cvv_retry_count    0.062835
14  is_ai_generated_scam_attempt_True    0.050635
15     billing_shipping_mismatch_True    0.048064
18               is_new_merchant_True    0.047073
19        is_foreign_transaction_True    0.046737
25      auth_method_No Authentication    0.046491
17                      used_vpn_True    0.037482
12                merchant_risk_score    0.033424
9                      velocity_score    0.027407
28                channel_Contactless    0.025175
13                     prior_disputes    0.018620
10                   time_of_day_hour    0.017265
41           merchant_category_Gaming    0.016544
38                 device_type_iPhone    0.015647
42       merchant_category_Gift Cards    0.015460
43        merchant_category_Groceries    0.015141
27                    auth_method_PIN    0.014977
5                     card_age_months    0.014840

In [81]:
model2.fit(x, y)

importance = pd.DataFrame({
    "Feature": x.columns,
    "Importance": model2.feature_importances_
})

importance = importance.sort_values(by="Importance", ascending=False)
print(importance.head(20))

                              Feature  Importance
16           ip_country_mismatch_True    0.074807
24              auth_method_Biometric    0.063059
8                     cvv_retry_count    0.062835
14  is_ai_generated_scam_attempt_True    0.050635
15     billing_shipping_mismatch_True    0.048064
18               is_new_merchant_True    0.047073
19        is_foreign_transaction_True    0.046737
25      auth_method_No Authentication    0.046491
17                      used_vpn_True    0.037482
12                merchant_risk_score    0.033424
9                      velocity_score    0.027407
28                channel_Contactless    0.025175
13                     prior_disputes    0.018620
10                   time_of_day_hour    0.017265
41           merchant_category_Gaming    0.016544
38                 device_type_iPhone    0.015647
42       merchant_category_Gift Cards    0.015460
43        merchant_category_Groceries    0.015141
27                    auth_method_PIN    0.014977
5                     card_age_months    0.014840

In [79]:
model.fit(x, y)

importance = pd.DataFrame({
    "Feature": x.columns,
    "Importance": model.feature_importances_
})

importance = importance.sort_values(by="Importance", ascending=False)
print(importance.head(20))

                              Feature  Importance
16           ip_country_mismatch_True    0.074807
24              auth_method_Biometric    0.063059
8                     cvv_retry_count    0.062835
14  is_ai_generated_scam_attempt_True    0.050635
15     billing_shipping_mismatch_True    0.048064
18               is_new_merchant_True    0.047073
19        is_foreign_transaction_True    0.046737
25      auth_method_No Authentication    0.046491
17                      used_vpn_True    0.037482
12                merchant_risk_score    0.033424
9                      velocity_score    0.027407
28                channel_Contactless    0.025175
13                     prior_disputes    0.018620
10                   time_of_day_hour    0.017265
41           merchant_category_Gaming    0.016544
38                 device_type_iPhone    0.015647
42       merchant_category_Gift Cards    0.015460
43        merchant_category_Groceries    0.015141
27                    auth_method_PIN    0.014977
5                     card_age_months    0.014840

In [83]:
df["is_fraud"].value_counts(normalize=True) * 100

is_fraud
0    98.305
1     1.695
Name: proportion, dtype: float64

Not Good Dataset this dataset is imbalanced::