<a href="https://colab.research.google.com/github/Shambhuraje1919/Machine_Learning_Paractice/blob/main/Date_formatting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import os

In [57]:
import pandas as pd
import numpy as np

In [23]:
path = "/orders (1).csv"

In [24]:
df = pd.read_csv("/orders (1).csv")

In [25]:
df.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [28]:
date = df

In [29]:
# Converting to datetime datatype
date['date'] = pd.to_datetime(date['date'])

In [31]:
date['year'] = date['date'].dt.year

In [42]:
date.head()

        date  product_id  city_id  orders  year     month  week
0 2019-12-10        5628       25       3  2019  December    10
1 2018-08-15        3646       14     157  2018    August    15
2 2018-10-23        1859       25       1  2018   October    23
3 2019-08-17        7292       25       1  2019    August    17
4 2019-01-06        4344       25       3  2019   January     6

In [41]:
date['month'] = date['date'].dt.month_name()
df.head(2)

        date  product_id  city_id  orders  year     month  week
0 2019-12-10        5628       25       3  2019  December    10
1 2018-08-15        3646       14     157  2018    August    15

In [45]:
date['date_day'] = date['date'].dt.day
date.head(2)

        date  product_id  city_id  orders  year     month  week  date_day
0 2019-12-10        5628       25       3  2019  December    10        10
1 2018-08-15        3646       14     157  2018    August    15        15

In [49]:
date["No_Ofweek"] = date['date'].dt.day_of_week
date.head(2)

,date,product_id,city_id,orders,year,month,week,date_day,No_Ofweek
0,2019-12-10,5628,25,3,2019,December,10,10,1
1,2018-08-15,3646,14,157,2018,August,15,15,2

In [52]:
date["day_name"] = date['date'].dt.day_name()
df.head()

,date,product_id,city_id,orders,year,month,week,date_day,No_Ofweek,day_name
0,2019-12-10,5628,25,3,2019,December,10,10,1,Tuesday
1,2018-08-15,3646,14,157,2018,August,15,15,2,Wednesday
2,2018-10-23,1859,25,1,2018,October,23,23,1,Tuesday
3,2019-08-17,7292,25,1,2019,August,17,17,5,Saturday
4,2019-01-06,4344,25,3,2019,January,6,6,6,Sunday

In [54]:
date = date.drop(["product_id","city_id"],axis=1)

In [55]:
date.head(2)

        date  orders  year     month  week  date_day  No_Ofweek   day_name
0 2019-12-10       3  2019  December    10        10          1    Tuesday
1 2018-08-15     157  2018    August    15        15          2  Wednesday

In [59]:
date['date_is_weekend'] = np.where(date['day_name'].isin(['Sunday', 'Saturday']), 1,0)

In [60]:
date.head(2)

,date,orders,year,month,week,date_day,No_Ofweek,day_name,date_is_weekend
0,2019-12-10,3,2019,December,10,10,1,Tuesday,0
1,2018-08-15,157,2018,August,15,15,2,Wednesday,0

Its the practice for date and time values , usefull in many ecomerce datasets:

> You can do it 12 LPA