<a href="https://colab.research.google.com/github/Shambhuraje1919/Machine_Learning_Paractice/blob/main/MinMax%20_Standard_Scaler.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler , StandardScaler

In [20]:
df = pd.read_csv("/content/indian_realestate_dataset_1000.csv")
df.head()

,property_id,city,district,property_type,built_up_area_sqft,price_inr,price_per_sqft_inr,bedrooms,bathrooms,age_years,...,annual_rental_yield_pct,price_category,estimated_roi_5yr_pct,listing_date,days_on_market,status,registration_days,is_gated_community,has_maintenance_fee,monthly_maintenance_inr
0,PROP00001,Chennai,Anna Nagar,Apartment,1526,10000000,6553,2,1,4,...,4.20,Premium,46.02,2024-10-17,215,Available,169,True,False,0
1,PROP00002,Mumbai,Bandra,Studio,424,50000000,117924,1,1,6,...,4.61,Luxury,48.07,2025-01-29,283,Available,50,False,False,100000
2,PROP00003,Chennai,Anna Nagar,Apartment,1333,10000000,7501,3,1,27,...,3.71,Premium,43.55,2024-06-27,312,Available,48,True,True,20000
3,PROP00004,Pune,Viman Nagar,Independent House,4121,15000000,3639,3,2,26,...,3.42,Premium,42.11,2024-10-11,336,Rented,84,False,False,0
4,PROP00005,Bangalore,Indiranagar,Villa,4020,30000000,7462,5,3,28,...,3.31,Luxury,41.53,2025-12-02,198,Sold,46,False,False,0

In [21]:
print("original data")
df.head()

original data

,property_id,city,district,property_type,built_up_area_sqft,price_inr,price_per_sqft_inr,bedrooms,bathrooms,age_years,...,annual_rental_yield_pct,price_category,estimated_roi_5yr_pct,listing_date,days_on_market,status,registration_days,is_gated_community,has_maintenance_fee,monthly_maintenance_inr
0,PROP00001,Chennai,Anna Nagar,Apartment,1526,10000000,6553,2,1,4,...,4.20,Premium,46.02,2024-10-17,215,Available,169,True,False,0
1,PROP00002,Mumbai,Bandra,Studio,424,50000000,117924,1,1,6,...,4.61,Luxury,48.07,2025-01-29,283,Available,50,False,False,100000
2,PROP00003,Chennai,Anna Nagar,Apartment,1333,10000000,7501,3,1,27,...,3.71,Premium,43.55,2024-06-27,312,Available,48,True,True,20000
3,PROP00004,Pune,Viman Nagar,Independent House,4121,15000000,3639,3,2,26,...,3.42,Premium,42.11,2024-10-11,336,Rented,84,False,False,0
4,PROP00005,Bangalore,Indiranagar,Villa,4020,30000000,7462,5,3,28,...,3.31,Luxury,41.53,2025-12-02,198,Sold,46,False,False,0

In [22]:
area_scaler = MinMaxScaler()
price_Scaler = StandardScaler()
print(df.columns.to_list())

['property_id', 'city', 'district', 'property_type', 'built_up_area_sqft', 'price_inr', 'price_per_sqft_inr', 'bedrooms', 'bathrooms', 'age_years', 'facing', 'amenities', 'amenities_count', 'walkability_score', 'monthly_rental_estimate_inr', 'annual_rental_yield_pct', 'price_category', 'estimated_roi_5yr_pct', 'listing_date', 'days_on_market', 'status', 'registration_days', 'is_gated_community', 'has_maintenance_fee', 'monthly_maintenance_inr']

In [24]:
df["built_up_area_sqft"] = MinMaxScaler().fit_transform(df[["built_up_area_sqft"]])
df["price_inr"] = StandardScaler().fit_transform(df[["price_inr"]])

In [25]:
df.head()

,property_id,city,district,property_type,built_up_area_sqft,price_inr,price_per_sqft_inr,bedrooms,bathrooms,age_years,...,annual_rental_yield_pct,price_category,estimated_roi_5yr_pct,listing_date,days_on_market,status,registration_days,is_gated_community,has_maintenance_fee,monthly_maintenance_inr
0,PROP00001,Chennai,Anna Nagar,Apartment,0.130734,-1.078295,6553,2,1,4,...,4.20,Premium,46.02,2024-10-17,215,Available,169,True,False,0
1,PROP00002,Mumbai,Bandra,Studio,0.017650,1.622569,117924,1,1,6,...,4.61,Luxury,48.07,2025-01-29,283,Available,50,False,False,100000
2,PROP00003,Chennai,Anna Nagar,Apartment,0.110929,-1.078295,7501,3,1,27,...,3.71,Premium,43.55,2024-06-27,312,Available,48,True,True,20000
3,PROP00004,Pune,Viman Nagar,Independent House,0.397024,-0.740687,3639,3,2,26,...,3.42,Premium,42.11,2024-10-11,336,Rented,84,False,False,0
4,PROP00005,Bangalore,Indiranagar,Villa,0.386660,0.272137,7462,5,3,28,...,3.31,Luxury,41.53,2025-12-02,198,Sold,46,False,False,0