<a href="https://colab.research.google.com/github/Shambhuraje1919/Machine_Learning_Paractice/blob/main/Polars_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import polars as pl

In [2]:
data = {
    "restaurant_name": ["Tandoor House", "Copper Deck", "Biryani By Kilo", "Spice Junction", "Urban Cafe"],
    "city": ["Chennai", "Delhi", "Delhi", "Pune", "Delhi"],
    "swiggy_rating": [4.0, 3.9, 4.4, 4.1, 3.6],
    "zomato_rating": [3.7, 4.1, 4.5, 4.0, 3.8],
    "avg_cost": [310, 450, 600, 250, 200]
}

In [4]:
df = pl.DataFrame(data)

In [5]:
df

shape: (5, 5)
┌─────────────────┬─────────┬───────────────┬───────────────┬──────────┐
│ restaurant_name ┆ city    ┆ swiggy_rating ┆ zomato_rating ┆ avg_cost │
│ ---             ┆ ---     ┆ ---           ┆ ---           ┆ ---      │
│ str             ┆ str     ┆ f64           ┆ f64           ┆ i64      │
╞═════════════════╪═════════╪═══════════════╪═══════════════╪══════════╡
│ Tandoor House   ┆ Chennai ┆ 4.0           ┆ 3.7           ┆ 310      │
│ Copper Deck     ┆ Delhi   ┆ 3.9           ┆ 4.1           ┆ 450      │
│ Biryani By Kilo ┆ Delhi   ┆ 4.4           ┆ 4.5           ┆ 600      │
│ Spice Junction  ┆ Pune    ┆ 4.1           ┆ 4.0           ┆ 250      │
│ Urban Cafe      ┆ Delhi   ┆ 3.6           ┆ 3.8           ┆ 200      │
└─────────────────┴─────────┴───────────────┴───────────────┴──────────┘

In [6]:
df.head(2)

shape: (2, 5)
┌─────────────────┬─────────┬───────────────┬───────────────┬──────────┐
│ restaurant_name ┆ city    ┆ swiggy_rating ┆ zomato_rating ┆ avg_cost │
│ ---             ┆ ---     ┆ ---           ┆ ---           ┆ ---      │
│ str             ┆ str     ┆ f64           ┆ f64           ┆ i64      │
╞═════════════════╪═════════╪═══════════════╪═══════════════╪══════════╡
│ Tandoor House   ┆ Chennai ┆ 4.0           ┆ 3.7           ┆ 310      │
│ Copper Deck     ┆ Delhi   ┆ 3.9           ┆ 4.1           ┆ 450      │
└─────────────────┴─────────┴───────────────┴───────────────┴──────────┘

In [7]:
df.tail(2)

shape: (2, 5)
┌─────────────────┬───────┬───────────────┬───────────────┬──────────┐
│ restaurant_name ┆ city  ┆ swiggy_rating ┆ zomato_rating ┆ avg_cost │
│ ---             ┆ ---   ┆ ---           ┆ ---           ┆ ---      │
│ str             ┆ str   ┆ f64           ┆ f64           ┆ i64      │
╞═════════════════╪═══════╪═══════════════╪═══════════════╪══════════╡
│ Spice Junction  ┆ Pune  ┆ 4.1           ┆ 4.0           ┆ 250      │
│ Urban Cafe      ┆ Delhi ┆ 3.6           ┆ 3.8           ┆ 200      │
└─────────────────┴───────┴───────────────┴───────────────┴──────────┘

In [9]:
df.is_empty()

False

In [10]:
df.is_duplicated()

shape: (5,)
Series: '' [bool]
[
	false
	false
	false
	false
	false
]

In [11]:
df.is_unique()

shape: (5,)
Series: '' [bool]
[
	true
	true
	true
	true
	true
]

In [12]:
df['avg_cost']

shape: (5,)
Series: 'avg_cost' [i64]
[
	310
	450
	600
	250
	200
]

In [14]:
df.mean()

shape: (1, 5)
┌─────────────────┬──────┬───────────────┬───────────────┬──────────┐
│ restaurant_name ┆ city ┆ swiggy_rating ┆ zomato_rating ┆ avg_cost │
│ ---             ┆ ---  ┆ ---           ┆ ---           ┆ ---      │
│ str             ┆ str  ┆ f64           ┆ f64           ┆ f64      │
╞═════════════════╪══════╪═══════════════╪═══════════════╪══════════╡
│ null            ┆ null ┆ 4.0           ┆ 4.02          ┆ 362.0    │
└─────────────────┴──────┴───────────────┴───────────────┴──────────┘

In [15]:
df.sum()

shape: (1, 5)
┌─────────────────┬──────┬───────────────┬───────────────┬──────────┐
│ restaurant_name ┆ city ┆ swiggy_rating ┆ zomato_rating ┆ avg_cost │
│ ---             ┆ ---  ┆ ---           ┆ ---           ┆ ---      │
│ str             ┆ str  ┆ f64           ┆ f64           ┆ i64      │
╞═════════════════╪══════╪═══════════════╪═══════════════╪══════════╡
│ null            ┆ null ┆ 20.0          ┆ 20.1          ┆ 1810     │
└─────────────────┴──────┴───────────────┴───────────────┴──────────┘

In [16]:
df.count()

shape: (1, 5)
┌─────────────────┬──────┬───────────────┬───────────────┬──────────┐
│ restaurant_name ┆ city ┆ swiggy_rating ┆ zomato_rating ┆ avg_cost │
│ ---             ┆ ---  ┆ ---           ┆ ---           ┆ ---      │
│ u32             ┆ u32  ┆ u32           ┆ u32           ┆ u32      │
╞═════════════════╪══════╪═══════════════╪═══════════════╪══════════╡
│ 5               ┆ 5    ┆ 5             ┆ 5             ┆ 5        │
└─────────────────┴──────┴───────────────┴───────────────┴──────────┘

In [17]:
df.describe()

shape: (9, 6)
┌────────────┬─────────────────┬─────────┬───────────────┬───────────────┬────────────┐
│ statistic  ┆ restaurant_name ┆ city    ┆ swiggy_rating ┆ zomato_rating ┆ avg_cost   │
│ ---        ┆ ---             ┆ ---     ┆ ---           ┆ ---           ┆ ---        │
│ str        ┆ str             ┆ str     ┆ f64           ┆ f64           ┆ f64        │
╞════════════╪═════════════════╪═════════╪═══════════════╪═══════════════╪════════════╡
│ count      ┆ 5               ┆ 5       ┆ 5.0           ┆ 5.0           ┆ 5.0        │
│ null_count ┆ 0               ┆ 0       ┆ 0.0           ┆ 0.0           ┆ 0.0        │
│ mean       ┆ null            ┆ null    ┆ 4.0           ┆ 4.02          ┆ 362.0      │
│ std        ┆ null            ┆ null    ┆ 0.291548      ┆ 0.311448      ┆ 162.696036 │
│ min        ┆ Biryani By Kilo ┆ Chennai ┆ 3.6           ┆ 3.7           ┆ 200.0      │
│ 25%        ┆ null            ┆ null    ┆ 3.9           ┆ 3.8           ┆ 250.0      │
│ 50%        ┆ null            ┆ null    ┆ 4.0           ┆ 4.0           ┆ 310.0      │
│ 75%        ┆ null            ┆ null    ┆ 4.1           ┆ 4.1           ┆ 450.0      │
│ max        ┆ Urban Cafe      ┆ Pune    ┆ 4.4           ┆ 4.5           ┆ 600.0      │
└────────────┴─────────────────┴─────────┴───────────────┴───────────────┴────────────┘

In [19]:
df.sample()

shape: (1, 5)
┌─────────────────┬───────┬───────────────┬───────────────┬──────────┐
│ restaurant_name ┆ city  ┆ swiggy_rating ┆ zomato_rating ┆ avg_cost │
│ ---             ┆ ---   ┆ ---           ┆ ---           ┆ ---      │
│ str             ┆ str   ┆ f64           ┆ f64           ┆ i64      │
╞═════════════════╪═══════╪═══════════════╪═══════════════╪══════════╡
│ Copper Deck     ┆ Delhi ┆ 3.9           ┆ 4.1           ┆ 450      │
└─────────────────┴───────┴───────────────┴───────────────┴──────────┘

In [20]:
df.drop('city')

shape: (5, 4)
┌─────────────────┬───────────────┬───────────────┬──────────┐
│ restaurant_name ┆ swiggy_rating ┆ zomato_rating ┆ avg_cost │
│ ---             ┆ ---           ┆ ---           ┆ ---      │
│ str             ┆ f64           ┆ f64           ┆ i64      │
╞═════════════════╪═══════════════╪═══════════════╪══════════╡
│ Tandoor House   ┆ 4.0           ┆ 3.7           ┆ 310      │
│ Copper Deck     ┆ 3.9           ┆ 4.1           ┆ 450      │
│ Biryani By Kilo ┆ 4.4           ┆ 4.5           ┆ 600      │
│ Spice Junction  ┆ 4.1           ┆ 4.0           ┆ 250      │
│ Urban Cafe      ┆ 3.6           ┆ 3.8           ┆ 200      │
└─────────────────┴───────────────┴───────────────┴──────────┘

In [23]:
df.head()

shape: (5, 5)
┌─────────────────┬─────────┬───────────────┬───────────────┬──────────┐
│ restaurant_name ┆ city    ┆ swiggy_rating ┆ zomato_rating ┆ avg_cost │
│ ---             ┆ ---     ┆ ---           ┆ ---           ┆ ---      │
│ str             ┆ str     ┆ f64           ┆ f64           ┆ i64      │
╞═════════════════╪═════════╪═══════════════╪═══════════════╪══════════╡
│ Tandoor House   ┆ Chennai ┆ 4.0           ┆ 3.7           ┆ 310      │
│ Copper Deck     ┆ Delhi   ┆ 3.9           ┆ 4.1           ┆ 450      │
│ Biryani By Kilo ┆ Delhi   ┆ 4.4           ┆ 4.5           ┆ 600      │
│ Spice Junction  ┆ Pune    ┆ 4.1           ┆ 4.0           ┆ 250      │
│ Urban Cafe      ┆ Delhi   ┆ 3.6           ┆ 3.8           ┆ 200      │
└─────────────────┴─────────┴───────────────┴───────────────┴──────────┘

In [21]:
df.group_by('avg_cost')

In [31]:
result = df.filter((pl.col('city')=='Delhi') & (pl.col('avg_cost') > 300)).select(['restaurant_name','zomato_rating','swiggy_rating'])

In [32]:
result

shape: (2, 3)
┌─────────────────┬───────────────┬───────────────┐
│ restaurant_name ┆ zomato_rating ┆ swiggy_rating │
│ ---             ┆ ---           ┆ ---           │
│ str             ┆ f64           ┆ f64           │
╞═════════════════╪═══════════════╪═══════════════╡
│ Copper Deck     ┆ 4.1           ┆ 3.9           │
│ Biryani By Kilo ┆ 4.5           ┆ 4.4           │
└─────────────────┴───────────────┴───────────────┘

In [33]:
result = df.group_by("city").agg([
    pl.col("zomato_rating").mean().alias("avg_zomato"),
    pl.len().alias("total_count")
])

print(result)

shape: (3, 3)
┌─────────┬────────────┬─────────────┐
│ city    ┆ avg_zomato ┆ total_count │
│ ---     ┆ ---        ┆ ---         │
│ str     ┆ f64        ┆ u32         │
╞═════════╪════════════╪═════════════╡
│ Pune    ┆ 4.0        ┆ 1           │
│ Chennai ┆ 3.7        ┆ 1           │
│ Delhi   ┆ 4.133333   ┆ 3           │
└─────────┴────────────┴─────────────┘

In [42]:
res = df.with_columns(((pl.col('swiggy_rating')+ pl.col('zomato_rating'))/2).alias('Overall_rating')).filter(pl.col('Overall_rating')>4)

In [43]:
res

shape: (2, 6)
┌─────────────────┬───────┬───────────────┬───────────────┬──────────┬────────────────┐
│ restaurant_name ┆ city  ┆ swiggy_rating ┆ zomato_rating ┆ avg_cost ┆ Overall_rating │
│ ---             ┆ ---   ┆ ---           ┆ ---           ┆ ---      ┆ ---            │
│ str             ┆ str   ┆ f64           ┆ f64           ┆ i64      ┆ f64            │
╞═════════════════╪═══════╪═══════════════╪═══════════════╪══════════╪════════════════╡
│ Biryani By Kilo ┆ Delhi ┆ 4.4           ┆ 4.5           ┆ 600      ┆ 4.45           │
│ Spice Junction  ┆ Pune  ┆ 4.1           ┆ 4.0           ┆ 250      ┆ 4.05           │
└─────────────────┴───────┴───────────────┴───────────────┴──────────┴────────────────┘

In [44]:
result = df.with_columns(
    pl.when(pl.col("avg_cost") > 400)
    .then(pl.lit("High"))
    .when(pl.col("avg_cost") >= 250)
    .then(pl.lit("Medium"))
    .otherwise(pl.lit("Low"))
    .alias("cost_category")
)

print(result)

shape: (5, 6)
┌─────────────────┬─────────┬───────────────┬───────────────┬──────────┬───────────────┐
│ restaurant_name ┆ city    ┆ swiggy_rating ┆ zomato_rating ┆ avg_cost ┆ cost_category │
│ ---             ┆ ---     ┆ ---           ┆ ---           ┆ ---      ┆ ---           │
│ str             ┆ str     ┆ f64           ┆ f64           ┆ i64      ┆ str           │
╞═════════════════╪═════════╪═══════════════╪═══════════════╪══════════╪═══════════════╡
│ Tandoor House   ┆ Chennai ┆ 4.0           ┆ 3.7           ┆ 310      ┆ Medium        │
│ Copper Deck     ┆ Delhi   ┆ 3.9           ┆ 4.1           ┆ 450      ┆ High          │
│ Biryani By Kilo ┆ Delhi   ┆ 4.4           ┆ 4.5           ┆ 600      ┆ High          │
│ Spice Junction  ┆ Pune    ┆ 4.1           ┆ 4.0           ┆ 250      ┆ Medium        │
│ Urban Cafe      ┆ Delhi   ┆ 3.6           ┆ 3.8           ┆ 200      ┆ Low           │
└─────────────────┴─────────┴───────────────┴───────────────┴──────────┴───────────────┘