<a href="https://colab.research.google.com/github/Shambhuraje1919/Machine_Learning_Paractice/blob/main/practice4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [315]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("yasserh/titanic-dataset")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'titanic-dataset' dataset.
Path to dataset files: /kaggle/input/titanic-dataset

In [316]:
import pandas as pd
import os
import numpy as np
from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,confusion_matrix

In [317]:
os.listdir(path)

['Titanic-Dataset.csv']

In [318]:
original = pd.read_csv(os.path.join(path,'Titanic-Dataset.csv'))

In [319]:
original.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [320]:
df = original.drop(columns=['PassengerId','Name','Ticket','Fare'],axis=1)

In [321]:
df.head()

   Survived  Pclass     Sex   Age  SibSp  Parch Cabin Embarked
0         0       3    male  22.0      1      0   NaN        S
1         1       1  female  38.0      1      0   C85        C
2         1       3  female  26.0      0      0   NaN        S
3         1       1  female  35.0      1      0  C123        S
4         0       3    male  35.0      0      0   NaN        S

In [322]:
df['family'] = df['SibSp']+df['Parch']

In [323]:
df.head()

   Survived  Pclass     Sex   Age  SibSp  Parch Cabin Embarked  family
0         0       3    male  22.0      1      0   NaN        S       1
1         1       1  female  38.0      1      0   C85        C       1
2         1       3  female  26.0      0      0   NaN        S       0
3         1       1  female  35.0      1      0  C123        S       1
4         0       3    male  35.0      0      0   NaN        S       0

In [324]:
df =df.drop(columns=['SibSp','Parch'],axis=1)

In [325]:
df = df.drop('Cabin',axis=1)

In [326]:
df.head()

   Survived  Pclass     Sex   Age Embarked  family
0         0       3    male  22.0        S       1
1         1       1  female  38.0        C       1
2         1       3  female  26.0        S       0
3         1       1  female  35.0        S       1
4         0       3    male  35.0        S       0

In [327]:
df.isnull().mean()*100

Survived     0.000000
Pclass       0.000000
Sex          0.000000
Age         19.865320
Embarked     0.224467
family       0.000000
dtype: float64

In [328]:
## missing value fill up
upper = df['Age'].mean()+(3*df['Age'].std())
lower = df['Age'].mean()-(3*df['Age'].std())
si = SimpleImputer(strategy='mean')
sii = SimpleImputer(strategy='most_frequent')
print(upper," ",lower)

73.27860964406095   -13.88037434994331

In [329]:
df.isnull().mean()*100

Survived     0.000000
Pclass       0.000000
Sex          0.000000
Age         19.865320
Embarked     0.224467
family       0.000000
dtype: float64

In [330]:
df['Age'] = si.fit_transform(df[['Age']])

In [331]:
df[['Embarked']] =sii.fit_transform(df[['Embarked']])

In [332]:
imputer = SimpleImputer(strategy="mean")
le = LabelEncoder()
ohe = OneHotEncoder(sparse_output=False)

In [333]:
df['Sex'] = le.fit_transform(df['Sex'])

In [334]:
data = ohe.fit_transform(df[['Embarked']])
new_cat = ohe.get_feature_names_out(['Embarked'])
df[new_cat]=data

In [335]:
df = df.drop('Embarked',axis=1)

In [336]:
df.isnull().mean()*100

Survived      0.0
Pclass        0.0
Sex           0.0
Age           0.0
family        0.0
Embarked_C    0.0
Embarked_Q    0.0
Embarked_S    0.0
dtype: float64

In [337]:
x = df.drop('Survived',axis=1)

In [338]:
x.head()

   Pclass  Sex   Age  family  Embarked_C  Embarked_Q  Embarked_S
0       3    1  22.0       1         0.0         0.0         1.0
1       1    0  38.0       1         1.0         0.0         0.0
2       3    0  26.0       0         0.0         0.0         1.0
3       1    0  35.0       1         0.0         0.0         1.0
4       3    1  35.0       0         0.0         0.0         1.0

In [339]:
y = df[['Survived']]

In [340]:
y.head()

   Survived
0         0
1         1
2         1
3         1
4         0

In [341]:
x_train ,x_test ,y_train ,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [342]:
model1= LogisticRegression()
model2 =RandomForestClassifier(n_estimators=10,max_depth=50)

In [343]:
model1.fit(x_train,y_train)
model2.fit(x_train,y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.12/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

RandomForestClassifier(max_depth=50, n_estimators=10)

In [344]:
pred1 = model1.predict(x_test)
pred2 = model2.predict(x_test)

In [345]:
print(accuracy_score(y_test,pred1),"Logistic")
print(accuracy_score(y_test,pred2),"Random_forest")

0.8100558659217877 Logistic
0.8212290502793296 Random_forest

In [346]:
print(confusion_matrix(y_test,pred1))

[[90 15]
 [19 55]]

In [347]:
print(confusion_matrix(y_test,pred2))

[[93 12]
 [20 54]]