<a href="https://colab.research.google.com/github/Shambhuraje1919/Machine_Learning_Paractice/blob/main/Railway_failuer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [123]:
import os
import pandas as pd

In [124]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("shambhurajejagadale/indian-railway-failure-detection-and-maintenance100k")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'indian-railway-failure-detection-and-maintenance100k' dataset.
Path to dataset files: /kaggle/input/indian-railway-failure-detection-and-maintenance100k

In [125]:
os.listdir(path)

['indian_railway_predictive_maintenance_100k.csv',
 'indian_railway_failure_detection_maintenance_v2.csv']

In [126]:
#path = 'indian_railway_predictive_maintenance_100k.csv'

In [127]:
df = pd.read_csv(os.path.join(path,'indian_railway_predictive_maintenance_100k.csv'))

In [128]:
df.head()

,train_id,region,season,train_type,train_age_years,average_speed_kmph,distance_travelled_km,track_temperature_c,rail_wear_mm,track_vibration_level,...,load_factor_percent,daily_trips,delay_minutes,last_maintenance_days,inspection_score,sensor_health_index,failure_type,maintenance_required,failure_severity,risk_score
0,1,Central Railway,Winter,Freight,18,93.911426,1088075,30.385539,11.267384,5.017916,...,59.221583,16,10.678221,75.0,81.614028,48.229938,NaN,0,NaN,66.621259
1,2,South Central Railway,Monsoon,Freight,3,83.985560,872233,39.700773,10.452440,NaN,...,62.512150,20,12.612107,182.0,94.538873,56.726790,NaN,0,NaN,59.477828
2,3,Southern Railway,Monsoon,Express,25,70.446432,1215080,54.346229,10.794243,5.043626,...,59.385796,20,8.537663,161.0,82.556458,73.183802,NaN,0,NaN,59.666196
3,4,Northern Railway,Summer,Express,30,25.392441,1113903,16.019386,7.983677,2.156439,...,93.597861,8,6.582553,164.0,79.143388,74.426802,NaN,0,NaN,54.684494
4,5,Northern Railway,Monsoon,Express,12,95.504013,21787,22.709736,5.150874,6.056355,...,29.845147,2,20.180113,86.0,60.370621,99.282662,NaN,0,NaN,54.711521

In [129]:
df =df.drop('train_id',axis=1)

In [130]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100300 entries, 0 to 100299
Data columns (total 34 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   region                  100300 non-null  object
 1   season                  100300 non-null  object
 2   train_type              100300 non-null  object
 3   train_age_years         100300 non-null  int64
 4   average_speed_kmph      100300 non-null  float64
 5   distance_travelled_km   100300 non-null  int64
 6   track_temperature_c     100300 non-null  float64
 7   rail_wear_mm            100300 non-null  float64
 8   track_vibration_level   94280 non-null   float64
 9   ballast_condition       100300 non-null  object
 10  track_curvature_degree  100300 non-null  float64
 11  ambient_temperature_c   100300 non-null  float64
 12  humidity_percent        95292 non-null   float64
 13  rainfall_mm             92280 non-null   float64
 14  wind_speed_kmph         93290 non-null   float64
 15  wheel_wear_percent      97288 non-null   float64
 16  axle_temperature_c      94286 non-null   float64
 17  brake_pressure_psi      100300 non-null  float64
 18  brake_pad_wear_percent  96289 non-null   float64
 19  bearing_temperature_c   93276 non-null   float64
 20  battery_voltage         96289 non-null   float64
 21  traction_motor_temp_c   95286 non-null   float64
 22  signal_system_status    100300 non-null  object
 23  power_consumption_kw    100300 non-null  float64
 24  load_factor_percent     99297 non-null   float64
 25  daily_trips             100300 non-null  int64
 26  delay_minutes           98297 non-null   float64
 27  last_maintenance_days   97291 non-null   float64
 28  inspection_score        100300 non-null  float64
 29  sensor_health_index     100300 non-null  float64
 30  failure_type            20264 non-null   object
 31  maintenance_required    100300 non-null  int64
 32  failure_severity        20264 non-null   object
 33  risk_score              100300 non-null  float64
dtypes: float64(23), int64(4), object(7)
memory usage: 26.0+ MB

In [131]:
df.describe()

,train_age_years,average_speed_kmph,distance_travelled_km,track_temperature_c,rail_wear_mm,track_vibration_level,track_curvature_degree,ambient_temperature_c,humidity_percent,rainfall_mm,...,traction_motor_temp_c,power_consumption_kw,load_factor_percent,daily_trips,delay_minutes,last_maintenance_days,inspection_score,sensor_health_index,maintenance_required,risk_score
count,100300.000000,100300.000000,1.003000e+05,100300.000000,100300.000000,94280.000000,100300.000000,100300.000000,95292.000000,92280.000000,...,95286.000000,100300.000000,99297.000000,100300.000000,98297.000000,97291.000000,100300.000000,100300.000000,100300.000000,100300.000000
mean,15.466052,75.000459,7.520451e+05,38.000384,7.983546,4.007977,7.978934,30.016028,59.917398,20.022832,...,75.098120,799.952912,64.669395,12.465543,16.023809,182.474556,77.868208,79.347010,0.202034,57.779099
std,8.625105,19.941000,4.315932e+05,11.955769,2.991982,1.492069,5.558993,7.933757,19.471704,14.169860,...,15.013677,248.093064,19.326057,6.907120,11.358678,105.172098,11.613677,13.850314,0.401519,7.674574
min,1.000000,20.000000,5.003000e+03,-5.000000,0.000000,0.000000,0.011962,0.000000,10.000000,0.052446,...,20.000000,100.000000,0.000000,1.000000,0.011772,1.000000,40.000000,14.416974,0.000000,30.696595
25%,8.000000,61.605096,3.782278e+05,29.933480,5.961386,3.002307,3.845972,24.653034,46.497790,9.602872,...,64.945015,632.435655,51.512574,6.000000,7.699682,91.000000,69.961323,69.798425,0.000000,52.401002
50%,15.000000,74.992668,7.508880e+05,37.966852,7.985173,4.007498,6.709405,30.006569,60.078016,16.812953,...,75.089266,800.702668,64.928438,12.000000,13.415300,183.000000,78.041663,79.973210,0.000000,57.649679
75%,23.000000,88.453576,1.126187e+06,46.129727,10.011973,5.013265,10.755527,35.428966,73.504797,26.980043,...,85.278009,967.606803,78.539665,18.000000,21.559530,273.000000,86.129940,90.130137,0.000000,62.957405
max,30.000000,160.000000,1.499989e+06,70.000000,21.043009,10.625342,30.000000,50.000000,100.000000,137.765477,...,145.145389,1837.864437,100.000000,24.000000,119.960986,364.000000,100.000000,100.000000,1.000000,97.838817

In [132]:
df.head()

,region,season,train_type,train_age_years,average_speed_kmph,distance_travelled_km,track_temperature_c,rail_wear_mm,track_vibration_level,ballast_condition,...,load_factor_percent,daily_trips,delay_minutes,last_maintenance_days,inspection_score,sensor_health_index,failure_type,maintenance_required,failure_severity,risk_score
0,Central Railway,Winter,Freight,18,93.911426,1088075,30.385539,11.267384,5.017916,Good,...,59.221583,16,10.678221,75.0,81.614028,48.229938,NaN,0,NaN,66.621259
1,South Central Railway,Monsoon,Freight,3,83.985560,872233,39.700773,10.452440,NaN,Good,...,62.512150,20,12.612107,182.0,94.538873,56.726790,NaN,0,NaN,59.477828
2,Southern Railway,Monsoon,Express,25,70.446432,1215080,54.346229,10.794243,5.043626,Good,...,59.385796,20,8.537663,161.0,82.556458,73.183802,NaN,0,NaN,59.666196
3,Northern Railway,Summer,Express,30,25.392441,1113903,16.019386,7.983677,2.156439,Good,...,93.597861,8,6.582553,164.0,79.143388,74.426802,NaN,0,NaN,54.684494
4,Northern Railway,Monsoon,Express,12,95.504013,21787,22.709736,5.150874,6.056355,Good,...,29.845147,2,20.180113,86.0,60.370621,99.282662,NaN,0,NaN,54.711521

In [133]:
df.isnull().mean()*100

region                     0.000000
season                     0.000000
train_type                 0.000000
train_age_years            0.000000
average_speed_kmph         0.000000
distance_travelled_km      0.000000
track_temperature_c        0.000000
rail_wear_mm               0.000000
track_vibration_level      6.001994
ballast_condition          0.000000
track_curvature_degree     0.000000
ambient_temperature_c      0.000000
humidity_percent           4.993021
rainfall_mm                7.996012
wind_speed_kmph            6.989033
wheel_wear_percent         3.002991
axle_temperature_c         5.996012
brake_pressure_psi         0.000000
brake_pad_wear_percent     3.999003
bearing_temperature_c      7.002991
battery_voltage            3.999003
traction_motor_temp_c      4.999003
signal_system_status       0.000000
power_consumption_kw       0.000000
load_factor_percent        1.000000
daily_trips                0.000000
delay_minutes              1.997009
last_maintenance_days      3.000000
inspection_score           0.000000
sensor_health_index        0.000000
failure_type              79.796610
maintenance_required       0.000000
failure_severity          79.796610
risk_score                 0.000000
dtype: float64

In [134]:
from sklearn.impute import SimpleImputer

In [135]:
imputer = SimpleImputer(strategy='mean')

In [136]:
df['track_vibration_level'] = imputer.fit_transform(df[['track_vibration_level']])

In [137]:
df['track_vibration_level'].isnull().mean()*100

np.float64(0.0)

In [138]:
df['humidity_percent'] = imputer.fit_transform(df[['humidity_percent']])

In [139]:
df['humidity_percent'].isnull().mean()*100

np.float64(0.0)

In [140]:
df.head(2)

,region,season,train_type,train_age_years,average_speed_kmph,distance_travelled_km,track_temperature_c,rail_wear_mm,track_vibration_level,ballast_condition,...,load_factor_percent,daily_trips,delay_minutes,last_maintenance_days,inspection_score,sensor_health_index,failure_type,maintenance_required,failure_severity,risk_score
0,Central Railway,Winter,Freight,18,93.911426,1088075,30.385539,11.267384,5.017916,Good,...,59.221583,16,10.678221,75.0,81.614028,48.229938,NaN,0,NaN,66.621259
1,South Central Railway,Monsoon,Freight,3,83.985560,872233,39.700773,10.452440,4.007977,Good,...,62.512150,20,12.612107,182.0,94.538873,56.726790,NaN,0,NaN,59.477828

In [141]:
df['rainfall_mm'] = imputer.fit_transform(df[['rainfall_mm']])

In [142]:
df['wind_speed_kmph'] = imputer.fit_transform(df[['wind_speed_kmph']])

In [143]:
df['wheel_wear_percent'] = imputer.fit_transform(df[['wheel_wear_percent']])

In [144]:
df['axle_temperature_c'] = imputer.fit_transform(df[['axle_temperature_c']])

In [145]:
df['brake_pad_wear_percent'] = imputer.fit_transform(df[['brake_pad_wear_percent']])

In [146]:
df['bearing_temperature_c'] = imputer.fit_transform(df[['bearing_temperature_c']])

In [147]:
df['battery_voltage'] = imputer.fit_transform(df[['battery_voltage']])

In [148]:
df['traction_motor_temp_c'] = imputer.fit_transform(df[['traction_motor_temp_c']])

In [149]:
df['load_factor_percent'] = imputer.fit_transform(df[['load_factor_percent']])

In [150]:
df['delay_minutes'] = imputer.fit_transform(df[['delay_minutes']])

In [151]:
 df['last_maintenance_days'] = imputer.fit_transform(df[['last_maintenance_days']])

In [152]:
df.isnull().mean()*100

region                     0.00000
season                     0.00000
train_type                 0.00000
train_age_years            0.00000
average_speed_kmph         0.00000
distance_travelled_km      0.00000
track_temperature_c        0.00000
rail_wear_mm               0.00000
track_vibration_level      0.00000
ballast_condition          0.00000
track_curvature_degree     0.00000
ambient_temperature_c      0.00000
humidity_percent           0.00000
rainfall_mm                0.00000
wind_speed_kmph            0.00000
wheel_wear_percent         0.00000
axle_temperature_c         0.00000
brake_pressure_psi         0.00000
brake_pad_wear_percent     0.00000
bearing_temperature_c      0.00000
battery_voltage            0.00000
traction_motor_temp_c      0.00000
signal_system_status       0.00000
power_consumption_kw       0.00000
load_factor_percent        0.00000
daily_trips                0.00000
delay_minutes              0.00000
last_maintenance_days      0.00000
inspection_score           0.00000
sensor_health_index        0.00000
failure_type              79.79661
maintenance_required       0.00000
failure_severity          79.79661
risk_score                 0.00000
dtype: float64

In [153]:
df = df.drop(columns=['failure_type','failure_severity'],axis=1)

In [154]:
df = df.drop('region',axis=1)

In [155]:
df.isnull().mean()*100

season                    0.0
train_type                0.0
train_age_years           0.0
average_speed_kmph        0.0
distance_travelled_km     0.0
track_temperature_c       0.0
rail_wear_mm              0.0
track_vibration_level     0.0
ballast_condition         0.0
track_curvature_degree    0.0
ambient_temperature_c     0.0
humidity_percent          0.0
rainfall_mm               0.0
wind_speed_kmph           0.0
wheel_wear_percent        0.0
axle_temperature_c        0.0
brake_pressure_psi        0.0
brake_pad_wear_percent    0.0
bearing_temperature_c     0.0
battery_voltage           0.0
traction_motor_temp_c     0.0
signal_system_status      0.0
power_consumption_kw      0.0
load_factor_percent       0.0
daily_trips               0.0
delay_minutes             0.0
last_maintenance_days     0.0
inspection_score          0.0
sensor_health_index       0.0
maintenance_required      0.0
risk_score                0.0
dtype: float64

In [156]:
df.describe()

,train_age_years,average_speed_kmph,distance_travelled_km,track_temperature_c,rail_wear_mm,track_vibration_level,track_curvature_degree,ambient_temperature_c,humidity_percent,rainfall_mm,...,traction_motor_temp_c,power_consumption_kw,load_factor_percent,daily_trips,delay_minutes,last_maintenance_days,inspection_score,sensor_health_index,maintenance_required,risk_score
count,100300.000000,100300.000000,1.003000e+05,100300.000000,100300.000000,100300.000000,100300.000000,100300.000000,100300.000000,100300.000000,...,100300.000000,100300.000000,100300.000000,100300.000000,100300.000000,100300.000000,100300.000000,100300.000000,100300.000000,100300.000000
mean,15.466052,75.000459,7.520451e+05,38.000384,7.983546,4.007977,7.978934,30.016028,59.917398,20.022832,...,75.098120,799.952912,64.669395,12.465543,16.023809,182.474556,77.868208,79.347010,0.202034,57.779099
std,8.625105,19.941000,4.315932e+05,11.955769,2.991982,1.446599,5.558993,7.933757,18.979362,13.591541,...,14.633596,248.093064,19.229183,6.907120,11.244688,103.582488,11.613677,13.850314,0.401519,7.674574
min,1.000000,20.000000,5.003000e+03,-5.000000,0.000000,0.000000,0.011962,0.000000,10.000000,0.052446,...,20.000000,100.000000,0.000000,1.000000,0.011772,1.000000,40.000000,14.416974,0.000000,30.696595
25%,8.000000,61.605096,3.782278e+05,29.933480,5.961386,3.076122,3.845972,24.653034,47.331743,10.206059,...,65.564962,632.435655,51.655217,6.000000,7.803009,94.000000,69.961323,69.798425,0.000000,52.401002
50%,15.000000,74.992668,7.508880e+05,37.966852,7.985173,4.007977,6.709405,30.006569,59.917398,18.246335,...,75.098120,800.702668,64.669395,12.000000,13.666676,182.474556,78.041663,79.973210,0.000000,57.649679
75%,23.000000,88.453576,1.126187e+06,46.129727,10.011973,4.940048,10.755527,35.428966,72.678840,25.795452,...,84.676403,967.606803,78.394035,18.000000,21.342987,271.000000,86.129940,90.130137,0.000000,62.957405
max,30.000000,160.000000,1.499989e+06,70.000000,21.043009,10.625342,30.000000,50.000000,100.000000,137.765477,...,145.145389,1837.864437,100.000000,24.000000,119.960986,364.000000,100.000000,100.000000,1.000000,97.838817

In [157]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100300 entries, 0 to 100299
Data columns (total 31 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   season                  100300 non-null  object
 1   train_type              100300 non-null  object
 2   train_age_years         100300 non-null  int64
 3   average_speed_kmph      100300 non-null  float64
 4   distance_travelled_km   100300 non-null  int64
 5   track_temperature_c     100300 non-null  float64
 6   rail_wear_mm            100300 non-null  float64
 7   track_vibration_level   100300 non-null  float64
 8   ballast_condition       100300 non-null  object
 9   track_curvature_degree  100300 non-null  float64
 10  ambient_temperature_c   100300 non-null  float64
 11  humidity_percent        100300 non-null  float64
 12  rainfall_mm             100300 non-null  float64
 13  wind_speed_kmph         100300 non-null  float64
 14  wheel_wear_percent      100300 non-null  float64
 15  axle_temperature_c      100300 non-null  float64
 16  brake_pressure_psi      100300 non-null  float64
 17  brake_pad_wear_percent  100300 non-null  float64
 18  bearing_temperature_c   100300 non-null  float64
 19  battery_voltage         100300 non-null  float64
 20  traction_motor_temp_c   100300 non-null  float64
 21  signal_system_status    100300 non-null  object
 22  power_consumption_kw    100300 non-null  float64
 23  load_factor_percent     100300 non-null  float64
 24  daily_trips             100300 non-null  int64
 25  delay_minutes           100300 non-null  float64
 26  last_maintenance_days   100300 non-null  float64
 27  inspection_score        100300 non-null  float64
 28  sensor_health_index     100300 non-null  float64
 29  maintenance_required    100300 non-null  int64
 30  risk_score              100300 non-null  float64
dtypes: float64(23), int64(4), object(4)
memory usage: 23.7+ MB

In [158]:
df['train_type'].unique()

array(['Freight', 'Express', 'Passenger', 'Metro'], dtype=object)

In [159]:
df['season'].unique()

array(['Winter', 'Monsoon', 'Summer'], dtype=object)

In [160]:
df['signal_system_status'].unique()

array(['Normal', 'Warning', 'Fault'], dtype=object)

In [161]:
df['ballast_condition'].unique()

array(['Good', 'Poor', 'Fair'], dtype=object)

In [162]:
df = pd.get_dummies(df,columns=['train_type','season','signal_system_status','ballast_condition'],drop_first=True)

In [163]:
df.head(1)

,train_age_years,average_speed_kmph,distance_travelled_km,track_temperature_c,rail_wear_mm,track_vibration_level,track_curvature_degree,ambient_temperature_c,humidity_percent,rainfall_mm,...,risk_score,train_type_Freight,train_type_Metro,train_type_Passenger,season_Summer,season_Winter,signal_system_status_Normal,signal_system_status_Warning,ballast_condition_Good,ballast_condition_Poor
0,18,93.911426,1088075,30.385539,11.267384,5.017916,2.5336,38.369258,74.214781,28.050316,...,66.621259,True,False,False,False,True,True,False,True,False

In [164]:
df.columns

Index(['train_age_years', 'average_speed_kmph', 'distance_travelled_km',
       'track_temperature_c', 'rail_wear_mm', 'track_vibration_level',
       'track_curvature_degree', 'ambient_temperature_c', 'humidity_percent',
       'rainfall_mm', 'wind_speed_kmph', 'wheel_wear_percent',
       'axle_temperature_c', 'brake_pressure_psi', 'brake_pad_wear_percent',
       'bearing_temperature_c', 'battery_voltage', 'traction_motor_temp_c',
       'power_consumption_kw', 'load_factor_percent', 'daily_trips',
       'delay_minutes', 'last_maintenance_days', 'inspection_score',
       'sensor_health_index', 'maintenance_required', 'risk_score',
       'train_type_Freight', 'train_type_Metro', 'train_type_Passenger',
       'season_Summer', 'season_Winter', 'signal_system_status_Normal',
       'signal_system_status_Warning', 'ballast_condition_Good',
       'ballast_condition_Poor'],
      dtype='object')

In [165]:
df.shape

(100300, 36)

In [166]:
'''REmoved the null values with means bcoz there is very small percent data is missing and also the categorical data is converted with numerical daata '''

'REmoved the null values with means bcoz there is very small percent data is missing and also the categorical data is converted with numerical daata '

In [167]:
df.sample(2)

,train_age_years,average_speed_kmph,distance_travelled_km,track_temperature_c,rail_wear_mm,track_vibration_level,track_curvature_degree,ambient_temperature_c,humidity_percent,rainfall_mm,...,risk_score,train_type_Freight,train_type_Metro,train_type_Passenger,season_Summer,season_Winter,signal_system_status_Normal,signal_system_status_Warning,ballast_condition_Good,ballast_condition_Poor
40875,15,49.735563,124662,38.315291,4.798578,5.141438,17.498495,38.248490,54.432576,22.393757,...,73.346232,False,False,True,False,False,False,True,False,False
9826,25,91.390701,1011746,55.591860,5.394843,4.666077,7.672328,12.575398,80.894696,29.176322,...,50.488042,False,False,True,True,False,True,False,True,False

In [168]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

In [169]:
model1 = LogisticRegression()

In [170]:
x = df.drop('maintenance_required',axis=1)

In [171]:
y = df[['maintenance_required']]

In [172]:
x_train , x_test , y_train,y_test = train_test_split(x,y,test_size=0.2,random_state= 44)

In [173]:
model1.fit(x_train,y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [174]:
y_pred = model1.predict(x_test)

In [175]:
from sklearn.metrics import accuracy_score

In [176]:
print("accuracy" ,accuracy_score(y_test,y_pred))

accuracy 0.7975573280159521

In [177]:
model2 = RandomForestClassifier(n_estimators=45,max_depth=7)

In [178]:
model2.fit(x_train,y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

RandomForestClassifier(max_depth=7, n_estimators=45)

In [179]:
pred2 = model2.predict(x_test)

In [180]:
print("random pred acc ",accuracy_score(y_test,pred2) )

random pred acc  0.8108673978065802

In [181]:
from sklearn.decomposition import PCA

In [182]:
pca = PCA(n_components=3)

In [191]:
from sklearn.decomposition import PCA

print(type(x_train))
print(type(x_test))

print(x_train.shape)
print(x_test.shape)

pca = PCA(n_components=3)

x_train_pca = pca.fit_transform(x_train)

print("n_features_in_:", pca.n_features_in_)
print("components shape:", pca.components_.shape)

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>
(80240, 35)
(20060, 35)
n_features_in_: 35
components shape: (3, 35)

In [192]:
x_train_pca = pca.fit_transform(x_train)
x_test_pca = pca.transform(x_test)

print(x_train_pca.shape)
print(x_test_pca.shape)

(80240, 3)
(20060, 3)

In [194]:
import pandas as pd

pca_df = pd.DataFrame(
    x_train_pca,
    columns=["PC1", "PC2", "PC3"]
)

pca_df["maintenance_required"] = y_train.reset_index(drop=True)

In [199]:
import plotly.express as px

fig = px.scatter_3d(
    pca_df,
    x="PC1",
    y="PC2",
    z="PC3",
    color="maintenance_required",
    color_discrete_map={
        0: "green",
        1: "red"
    },
    opacity=0.7,
    title="3D PCA Visualization - Railway Maintenance Prediction",
    labels={"maintenance_required": "Maintenance"}
)

fig.update_traces(marker=dict(size=3))

fig.update_layout(
    template="simple_white",
    scene=dict(
        xaxis_title="Principal Component 1",
        yaxis_title="Principal Component 2",
        zaxis_title="Principal Component 3"
    ),
    width=900,
    height=700
)

fig.show()